### ISSUE TITLE
OAuth internal redirects discard API prefixes

### ISSUE THREAD

**Issue by emilselroos** [feathersjs/feathers#2031] opened 2020-07-27 23:31 UTC
I am trying to implement Google OAuth authentication in my FeathersJS (4.5.7) application. I have an API listening to `/api/v1` prefix - done by wrapping the feathers application within another express application. (Similar to this [comment](https://github.com/feathersjs/feathers/issues/531#issuecomment-287153441))

### Expected behavior

Going to `/api/v1/oauth/google` should redirect users to `/api/v1/oauth/connect/google`.

### Actual behavior

Redirecting to `/oauth/connect/google`, discarding the API prefix and leading to `CANNOT GET /oauth/connect/google` page.

---

My authentication config in `config.json`

```
"authentication": {

	"path": "/authentication",
	"entity": "account",
	"entityId": "account_id",
	"service": "accounts",
	"secret": "SECRET",
	"authStrategies": [ "jwt", "oauth" ],

	"jwtOptions": {
	  "audience": "localhost",
	  "issuer": "feathers",
	  "algorithm": "HS256",
	  "expiresIn": "1d"
	},

	"oauth": {
		"redirect": "http://localhost:3000",
		
		"defaults": {
			"protocol": "http",
			"host": "localhost",
			"path": "/oauth",
			"transport": "session",
			"state": true
			
		},
		"google": {
			"key": "KEY",
			"secret": "SECRET",
			"scope": [ "email", "profile", "openid" ],
			"nonce": true,
			"redirect_uri": "http://localhost:3030/api/v1/oauth/google/callback"
		}
	}

  }
```

And my `authentication.js` file

```
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { expressOauth, OAuthStrategy } = require('@feathersjs/authentication-oauth');

class GoogleStrategy extends OAuthStrategy {
	async getEntityData (profile) {
		const baseData = await super.getEntityData(profile);

		return {
			...baseData,
			google_id: profile.googleId,
			profile_picture: profile.picture,
			email: profile.email,
			name: profile.given_name + ' ' + profile.family_name,
		}
	}

	async getRedirect(data) {
		return '/frontend';
	}
}

module.exports = app => {

	const authentication = new AuthenticationService(app);

	authentication.register('jwt', new JWTStrategy());
	authentication.register('google', new GoogleStrategy());
	
	app.use('/authentication', authentication);
	app.configure( expressOauth() );

}
```

**Comment by michaek** [comment] 2020-10-05 15:17
I was imagining it would be possible to pass in a `path` option to `expressOauth`, but it seems that despite merging passed settings and default before being invoked, it always reads from the configured defaults: https://github.com/feathersjs/feathers/blob/crow/packages/authentication-oauth/src/express.ts#L29 Were you thinking that the app would infer the path from its mount path?

**Comment by forgot** [comment] 2020-11-11 04:38
In my case, I have Feathers set to serve at `myawesomesite.com/api`, and an Angular app at `myawesomesite.com`. I think the problem is that Feathers doesn't realize it's not at the root, which makes sense because it shouldn't care.

I'm pretty new to all things web development, so I'm just spitballing here, but I'm wondering if the way some of the redirects are formed could be causing the problem.

Looking at the code [here](https://github.com/feathersjs/feathers/blob/40e2d0f31ff0387cc9bf989d3608a7867b8dcff1/packages/authentication-oauth/src/express.ts#L51) and [here](https://github.com/feathersjs/feathers/blob/40e2d0f31ff0387cc9bf989d3608a7867b8dcff1/packages/authentication-oauth/src/express.ts#L55), the redirects are relative. Since Feathers doesn't know it's not at the root of the site, clicking on `/api/oauth/github` in my site redirects to `myawesomesite.com/oauth/connect/github` instead of `myawesomesite.com/api/oauth/connect/github`. If I manually add in `/api`, it proceeds to the next link/step.

From what I understand reading the documentation for [`res.redirect`](https://expressjs.com/en/api.html#res.redirect), it acts like `res.location` if a relative link is passed, but can be overridden by putting in a fully-qualified URL. Would having those redirects be fully-qualified URLs help? Maybe by adding/calling something like [`getURL()`](https://github.com/feathersjs/feathers/blob/40e2d0f31ff0387cc9bf989d3608a7867b8dcff1/packages/authentication-oauth/src/index.ts#L53) from `index.ts` so that we end up with ``res.redirect(`${defaults.protocol}://${defaults.host}${path}/connect/${req.params.name}/callback?${qs.stringify(req.query)}`)`` instead?

**Comment by forgot** [comment] 2020-11-15 19:36
@daffl am I going in the wrong direction here, or is this an option? I made changes in a fork, and they pass all the tests.

**Comment by michaek** [comment] 2020-11-17 16:53
I believe @forgot is talking about changes from this commit: https://github.com/forgot/feathers/commit/fae83f593bf5f622286759db3ce1360759926626 It does not look to me like that will have an impact on the behavior associated with this issue, as it adds a scheme/host from configuration and does not affect the path.

@daffl Would you prefer an option for passing a path to expressOauth, using app.mountpath, or both (path taking precedence if passed)? I'll be happy to provide a PR with the desired behavior.

**Comment by forgot** [comment] 2020-11-22 06:51
I went that direction due to the fact that whatever path is set to redirects internally. In my case, even setting path to `api/oauth` still requires manually adding `/api` for it to succeed, resulting in `/api/api/oauth`. My understanding is that those changes would allow the redirect to succeed without breaking anything else, and would work for both apps that are mounted behind an Express app and those that are not.

I'm sure there is a better way to do this, but it's just the first thing that popped into my head once I realized that the redirects were internal to the Feathers app. I started commenting here as it was suggested that the issues may be related. If they are not, I can move my discussion back to my original issue.

**Comment by daffl** [comment] 2021-03-30 17:15
This has been fixed in Grant v5 and the Feathers 5 prerelease (`5.0.0-beta.0`) - it is now possible to set the following in your authentication configuration:

```json
{
  "authentication": {
    "oauth": {
      "defaults": {
        "prefix": "api/oauth"
      },
      "redirect": "/frontend",
      "google": {
        "key": "...",
        "secret": "...",
        "custom_params": { "access_type": "offline" }
      },
      "twitter": {
        "key": "...",
        "secret": "..."
      }
    }
  }
}
```

See the [migration guide](https://dove.docs.feathersjs.com/guides/migrating.html) for how to test the prerelease.

**Closed by daffl** 2021-03-30 17:15 UTC
Labels: Authentication, Bug

**Comment by nsainaney** [comment] 2022-10-04 07:47
@daffl: This seems to have regressed in `^5.0.0-pre.29`. I have:

```
        "oauth": {
            "defaults": {
                "prefix": "/api/oauth",
            },
            "redirect": "KOPANION_OAUTH_REDIRECT",
            "google": {
                "appId": "KOPANION_GOOGLE_APP_ID",
                "appKey": "KOPANION_GOOGLE_APP_KEY",
                 ...
```

The above worked in `^5.0.0-pre.26` but prefix is discarded in `^5.0.0-pre.29`. The following lines

https://github.com/feathersjs/feathers/blob/9231525a24bb790ba9c5d940f2867a9c727691c9/packages/authentication-oauth/src/index.ts#L35

https://github.com/feathersjs/feathers/blob/9231525a24bb790ba9c5d940f2867a9c727691c9/packages/authentication-oauth/src/index.ts#L37

https://github.com/feathersjs/feathers/blob/9231525a24bb790ba9c5d940f2867a9c727691c9/packages/authentication-oauth/src/index.ts#L44

Do not look at `defaults.prefix`. Will submit a PR
