### ISSUE TITLE
JWT refresh token when a call is triggered after the expiry

### ISSUE THREAD

**Issue by mkharibalaji** [feathersjs/feathers#546] opened 2017-04-08 10:32 UTC
Hi Guys,
       Is there a way to refresh the featherjs JWT token from the client side automatically if it expires untill he is explicitly logged out.
For Example if a call is triggered form the client after the expiry of the token,will the client handle the reauthentication process and trigger the call once again ?
```
const errorHandler = error => {
  app.authenticate({
    strategy: 'local',
    email: 'admin@feathersjs.com',
    password: 'admin'
  }).then(response => {
    // You are now authenticated again
  });
};
// Handle when auth fails during a reconnect or a transport upgrade
app.on('reauthentication-error', errorHandler)
```
I don't want to store the credentials on the client side in order to reauthenticate....Is there something else that could be done ?

**Comment by mkharibalaji** [comment] 2017-04-13 12:51
@daffl out of curiosity - any idea on the milestone when this would be implemented as i am able to see the notes in the feathers-authentication client code...

... // create accessToken
      // TODO (EK): Support refresh tokens
      // TODO (EK): This should likely be a hook
      // TODO (EK): This service can be datastore backed to support blacklists :)

**Comment by marshallswain** [comment] 2017-04-13 15:58
The coming milestone.  No timeline, yet.

**Comment by knappdev** [comment] 2017-05-06 00:22
Waiting on this feature. would help a lot in the client side

**Comment by daffl** [comment] 2017-12-15 05:08
Closing as a duplicate of https://github.com/feathersjs/authentication/issues/22

**Closed by daffl** 2017-12-15 05:08 UTC
