### ISSUE TITLE
(v4) should clientApp.logout fail if not yet logged in?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1449] opened 2019-07-10 15:59 UTC
### Steps to reproduce

Using either rest or socket client, create the client-side app.

Call `app.logout` before calling `app.authenticate`

We have a few places (in code and tests) that try to ensure browser is logged out before taking an action, but right now we don't have an explicit check that the user is logged in.  Wondering if this is a conscious regression/change in behavior or not.

### Expected behavior
Should succeed/not error out (this is pre-v4 behavior)

### Actual behavior
```
error: NotAuthenticated: Invalid authentication information (no `strategy` set)
    at new NotAuthenticated (/Users/joe/research/fv4/alt-strategy-name/node_modules/@feathersjs/errors/lib/index.js:93:17)
    at Object.<anonymous> (/Users/joe/research/fv4/alt-strategy-name/node_modules/@feathersjs/authentication/lib/core.js:150:23)
```

**Comment by jnardone** [comment] 2019-07-16 18:29
The more I see this the more I think the default behavior should be a silent failure vs. a 401 if there's no existing session (or the client-side logout shouldn't call the server if there's no state information to log out from...)

**Comment by daffl** [comment] 2019-07-19 16:20
Yep, makes sense, that seems to be the expected behaviour in existing applications. Will be fixed via #1473

**Comment by jnardone** [comment] 2019-07-19 17:01
awesome

**Closed** 2019-07-20 17:53 UTC

**Comment by jnardone** [comment] 2019-07-22 15:39
@daffl when will next prerelease be tagged?

**Comment by daffl** [comment] 2019-07-22 20:50
Once #1430 has been addressed.
