### ISSUE TITLE
event filter called multiple times.

### ISSUE THREAD

**Issue by elBarkey** [feathersjs/feathers#637] opened 2017-08-06 13:33 UTC
### Steps to reproduce
```javascript
app.service('message').filter({
 created:   function(data, connection, hook) {
  console.log(`userID: ${connection.user._id}, hook type: ${hook.type}, hook method: ${hook.method}`);     
 }
})
```

### Expected behavior
log event should be called only once ?

### Actual behavior
log event called in between 2-4 times randomly.

### System configuration

**Module versions** (feathers@2.1.3):

**NodeJS version**:  7.9.0

**Operating System**: Windows 7 x64

**Comment by elBarkey** [comment] 2017-08-06 13:56
I just realize that event filter is called for every connected client.
However it is still called at least twice per created message event for the same user connection.

**Comment by bertho-zero** [comment] 2017-08-07 10:53
You can close the issue if the issue is resolved.

**Closed** 2017-08-07 23:31 UTC
