### ISSUE TITLE
Optional Prepopulating Through url param

### ISSUE THREAD

**Issue by AkramEld** [feathersjs/feathers#1916] opened 2020-04-15 04:17 UTC
I am using feathers-hooks-common:

Lets say you have a Teams Model with:
`name: { type: String, required: true },
  playerIds: { type: Array, required: true },`

and you use "populate" to prepopulate with the players objects like so 
`const userRolesSchema = {
  include: {
    service: 'api/players',
    nameAs: 'players',
    parentField: 'playerIds',
    childField: '_id',
    asArray: true
  }
}`

Is there a way to pass a parameter to the teams api to not prepopulate it sometimes, lets say "/api/teams?players=no"

Thanks

**Comment by daffl** [comment] 2020-04-21 23:03
Closing as duplicate of https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/581.

**Closed by daffl** 2020-04-21 23:03 UTC
