### ISSUE TITLE
Problems mounting sub apps.

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#330] opened 2016-05-17 20:04 UTC
I have problems mounting a sub app.

I scaffolded the main app using the CLI. In the root directory, I created an "api" folder and scaffolded a product service. I then tried to import and mount the service. Although it did not out put errors, the routes I defined always resulted in 404s. Is there a better guideline for scaffolding and mounting sub apps? The example in the docs is just too vague. Thanks

./src/app.js
`````
...
app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( path.join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(services)
  .configure(middleware);

const apiV1 = require('./../api/src/app');
app.use('/v1', apiV1); // <--DOES NOT WORK
`````

./api/src/app.js

``````
const feathers = require('feathers');
const productService = require('./services/product');

const app = feathers().use('/products', productService);

module.exports = app;
`````

**Comment by daffl** [comment] 2016-05-18 04:05
Sub-apps are pretty separate. You might have to `app.configure(rest())` (and possibly all other middleware you want to use) in the sub-app as well:

```js
const feathers = require('feathers');
const rest = require('feathers-rest');
const productService = require('./services/product');

const app = feathers().configure(rest()).use('/products', productService);

module.exports = app;
```

If that solves the problem we'd really appreciate your help in updating the vague docs.

**Comment by kokujin** [comment] 2016-05-18 04:22
thanks @daffl , so that means the steps would be:

1. Scaffold the main app in the root folder using "feathers generate appName"
2. Create a sub folder in the root and scaffold the sub app there using "feathers generate subAppName"
3. Scaffold services as usual in the sub app folder
4. In the app.js file of the main app, import the sub app and mount it on a route as follows:

const subApp = require('./subAppFolder/src/app');
app.use('/v1', subApp);

Wold this be correct?

**Comment by kokujin** [comment] 2016-05-18 19:43
Just tried it out, sadly, that did not work either. Could you post some code, a small skeleton? Thanks

**Comment by daffl** [comment] 2016-05-19 00:13
There is a complete example that @ekryski pushed in https://github.com/feathersjs/feathers-demos/tree/master/examples/app-structure/sub-apps

**Comment by kokujin** [comment] 2016-05-20 22:00
Thanks @daffl , but the example in the link did work work either. It really would be great if one could use the feathers CLI to generate sub apps. Using express, its easy. This gist works without any adjustments or modifications, https://gist.github.com/focusaurus/5779340

**Comment by daffl** [comment] 2016-05-20 22:13
The example indeed does not work. Maybe @ekryski can fix it. Here is a working example:

```
const feathers = require('feathers');
const rest = require('feathers-rest');
const socketio = require('feathers-socketio');
const hooks = require('feathers-hooks');
const authentication = require('feathers-authentication');
const bodyParser = require('body-parser');
const handler = require('feathers-errors/handler');

const v1 = feathers()
  .configure(rest())
  .use('/todos', {
  get(id) {
    return Promise.resolve({
      id,
      version: 1,
      text: `You have to do ${id}!`
    });
  }
});

const v2 = feathers()
  .configure(rest())
  .use('/todos', {
    get(id) {
      return Promise.resolve({
        id,
        version: 2,
        text: `You really have to do ${id}!`
      });
    }
  });

const app = feathers();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.configure(hooks());
app.configure(rest());
app.configure(socketio());
app.use(handler());

app.use('/api/v1', v1);
app.use('/api/v2', v2);

app.listen(3030);
```

Now, http://localhost/api/v1/todos/dishes will show version 1 and http://localhost/api/v2/todos/laundry version 2. This is pretty much the same as in Express. You just need to make sure that the sub-app has the REST handler and other middleware you would like to use configured properly.

**Comment by kokujin** [comment] 2016-05-20 23:13
Not quite @daffl , I did a quick check, in an existing scaffolded project, I used your code in the app.js

`````
...
// snip!
const userService = require('./services/user');

const v3 = feathers()
    .configure(rest()) // REST configured here
    .use('/users', userService);

const app = feathers();
app.configure(configuration(path.join(__dirname, '..')));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.configure(hooks());
app.configure(rest()); // REST configured here too?
app.configure(socketio());
app.use('/api/v1', v1);
app.use('/api/v2', v2);
app.use('/api/v3', v3);
app.use(handler());

module.exports = app;

````

If I try to GET a route on api/v3, as in localhost:3030/api/v3/users

 I get this:
````
{
  "name": "GeneralError",
  "message": "Cannot read property 'get' of undefined",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}
`````

How do I correct this issue and why is REST configured so often?

Thanks

**Comment by daffl** [comment] 2016-05-20 23:34
You have to configure the REST handler for every app because otherwise it won't set up any routes. Services do not always have to represent REST routes, they only will if you configure the `feathers-rest` provider. You can use them only internally or only via websockets (or anything else) just as well. Again, here is a complete sub-app setup with a built-in service that I tested and that definitely works:

Run

> npm install feathers feathers-rest feathers-socketio feathers-hooks feathers-memory body-parser feathers-errors

Then add the `app.js` below and run `node app`:

```js
const feathers = require('feathers');
const rest = require('feathers-rest');
const socketio = require('feathers-socketio');
const hooks = require('feathers-hooks');
const memory = require('feathers-memory');
const bodyParser = require('body-parser');
const handler = require('feathers-errors/handler');

const v1 = feathers()
  .configure(rest())
  .use('/todos', memory());

const v2 = feathers()
  .configure(rest())
  .use('/todos', memory());

const app = feathers();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.configure(hooks());
app.configure(rest());
app.configure(socketio());
app.use('/api/v1', v1);
app.use('/api/v2', v2);
app.use(handler());

app.listen(3030);
```

You will have to do a little bit of digging why it wouldn't work for your specific setup or create a Git repository with a minimum breaking example to reproduce the problem.

**Comment by kokujin** [comment] 2016-05-21 01:52
There is a misunderstanding here. Your example works, no question, but it's hardly the realistic way I would want to use FeathersJs. I like the CLI , I want to scaffold my projects, models and services with it. Your example, although it works, loses all of the benefits of a scaffolded application.

Thanks anyways.

**Comment by daffl** [comment] 2016-05-21 02:36
The generated applications export their mountable `app` object in `src/app`. So, to use a scaffolded app as a sub-app, generate two different applications. Then install the sub-app in the main application via `npm install path/to/subapp` (or via [npm link](https://docs.npmjs.com/cli/link)). After that, require `subapp/src/app.js` with `const subApp = require('subapp/src/app')` and mount it:

```js
// ...

const app = feathers();
const subapp = require('subapp/src/app');

app.configure(configuration(path.join(__dirname, '..')));

app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( path.join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  // THIS
  .use('/api/v2', subapp)
  .configure(services)
  .configure(middleware);

module.exports = app;
```

One improvement we could make in the generator would be to set the main to `src/app` instead of `src/index`.

**Comment by ekryski** [comment] 2016-05-21 02:44
We actually don't really encourage sub-apps. IMHO when you get to the point that you want to decouple things like that then they should be treated as separate apps. We'll have more documentation on how to split your apps up into microservices soon.

Looks like @daffl gave you lots of pointers here and the problem is not really with Feathers, just more of a personal preference so I'm going to close this now.

**Closed by ekryski** 2016-05-21 02:44 UTC

**Comment by kokujin** [comment] 2016-05-21 06:08
Thanks for your patience @daffl 

> Looks like @daffl gave you lots of pointers here and the problem is not really with Feathers, just more of a personal preference so I'm going to close this now

I beg to differ @ekryski, sub apps were mentioned in the docs and you even have code that tries to illustrate ths, the link that @daffl  sent me to.

In all, I would be scaffolding apps into separate project folders, I have tried that and that works

**Comment by ekryski** [comment] 2016-05-23 20:12
@kokujin the generator was never intended to scaffold multiple sub-apps. If you want to do sub-apps you need to do some work manually. Sorry.

I've updated the examples in feathers-demos. My bad that they weren't working. I guess when I committed them they weren't completely fleshed out. Thanks for pointing that out.

**Comment by kokujin** [comment] 2016-05-24 17:55
great! Thanks
