### ISSUE TITLE
Inconsistency with $gt and $gte

### ISSUE THREAD

**Issue by gabrielstuff** [feathersjs/feathers#868] opened 2018-05-16 14:59 UTC
Hi ! Thanks for this great project. I really like to work with it. I have a little concern regarding consistency of query.

Please find bellow our issue:

### A mongodb service 

Our service store records containing this:

```
{
            "_id": "5afc0af32f6238bed1b2516d",
            "slot": "62",
            "motor": "174",
            "qty": "7"
}
```

So `qty` is store as a string even if it is a number

While using a query with the `$gt` or `$gte` operator, the result are not the same with query method and with a http `GET`.

### Steps to reproduce

Querying a URI using the http protocole result in **expected behavior**:

http://localhost:6090/slots?qty[$gt]=0
and
http://localhost:6090/slots?qty[$gt]="0"

works ok, indifferently.

Querying the same service with `.find()` method on server side result in empty response.

```
query: {
  qty: {
    $gt: 0
  }
}
```

### Expected behaviour

Either using the route or the query inside the server should return result or no result.

### Fix

We need to query with a string and it works.

```
query: {
  qty: {
    $gt: '0'
  }
}
```

### System configuration

- `MongoDB shell version v3.6.4`
- `node 8.9.1`
- `macOS High Sierra`

**Module versions** (especially the part that's not working):

- `"feathers-mongodb": "^3.0.1"`
- `"@feathersjs/express": "^1.2.2"`
- `"@feathersjs/feathers": "^3.1.4"`

**Comment by daffl** [comment] 2018-05-16 17:16
This is a duplicate of https://github.com/feathersjs/feathers/issues/757. When using plain MongoDB the query fields have to be converted to the same type as the data that is being queried. There are examples for how to convert it in a hook in the linked issue.

This is only the case when using the plain MongoDB adapter and REST URLs. It will work when either using websockets or an ORM/ODM that supports schema conversions like Mongoose.

**Closed** 2018-05-17 15:32 UTC

**Comment by gabrielstuff** [comment] 2018-06-08 07:08
Thanks. Perfectly clear. Maybe somewhere we should at this in the docs / faq ?

**Comment by gabrielstuff** [comment] 2018-06-11 13:03
Thanks.
