### ISSUE TITLE
feathersjs typescript types - the '.watch()' is not in the feathers typings

### ISSUE THREAD

**Issue by Ismail-codinglab** [feathersjs/feathers#1454] opened 2019-07-11 14:51 UTC
### Steps to reproduce

1. install @types/feathersjs__feathers@3.1.5
2. `let service = this.feathers.service('users') as Service<any>`
3. `service.watch()` <-- watch is not defined in typings

### Expected behavior
Watch method of feathers-reactive is not in the typescript typings for Angular 2+

### Actual behavior
Watch method of feathers-reactive being added in the typescript typings for Angular 2+

**Comment by daffl** [comment] 2019-07-11 16:25
Duplicate of https://github.com/feathersjs-ecosystem/feathers-reactive/issues/164

**Closed by daffl** 2019-07-11 16:25 UTC
