### ISSUE TITLE
login event emit twice for same user using socket.io

### ISSUE THREAD

**Issue by raushansingh629** [feathersjs/feathers#1174] opened 2019-01-18 18:29 UTC
### Steps to reproduce
setup authentication using feather-client(socket.io)  and add login event to feather api-server(setup feather server using feather express and socket modules). 
when the user authenticates from UI, feather emits the login event twice for the same user. 

### Expected behavior
it should emit one login event when the same user authenticates from UI.  
### Actual behavior
when user login through app feather server emits login event twice for the same user. 

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
**feather server:**
   "@feathersjs/authentication": "2.1.6",
    "@feathersjs/authentication-jwt": "2.0.1",
    "@feathersjs/authentication-local": "1.2.1",
    "@feathersjs/configuration": "1.0.2",
    "@feathersjs/express": "1.2.2",
    "@feathersjs/feathers": "3.2.3",
    "@feathersjs/socketio": "3.2.1"
**feather-client:**
      "@feathersjs/client@3.7.6"
**NodeJS version**:
8.9.3
**Operating System**:
host: Ubuntu 16.04.5 LTS (x86_64)
container image: alpine:3.7

I know feather socket.io uses **pooling** transport first after that then it upgrades to **web socket** transport.
so is there any to prevent the double login event?
your help will be appreciated.

**Comment by daffl** [comment] 2019-01-18 20:53
This is a confirmed bug, originally reported in https://github.com/feathersjs/authentication/issues/673. Keeping this one open to track things here.

**Comment by vinaykharecha** [comment] 2019-01-21 08:44
@daffl ,

I noticed that this happens because of socket transport **upgrade** from **polling to websocket** that's when you will see two login events. 

another thing i noticed that if i run feathers server and client **locally** than **i don't see two login event** i.e in same local network; if i put client and server apart via **internet** than only **i see two login events** that's may be because of network latency.

I figured two possible **workaround** for this to prevent two login events.

1.  In feathers client if you configure socket with **upgrade false** than you will not see two login events
2. Or if you put configure transport in this order than also you will not see two login events **transports: [ 'websocket','polling']**

I've right now used transport in revers order i.e. fallback approach; so i'm not getting two login events.
I know this is temporary fix ideally socket should prevent that OR it should fire two logout in conjunction to that

**Comment by dottodot** [comment] 2019-01-22 14:52
Could this be related to why I keep getting an error of `app.emit is not a function` when users attempt to login?

**Comment by daffl** [comment] 2019-02-07 18:44
Thanks for digging into this @vinaykharecha. This

**Comment by matiaslopezd** [comment] 2019-02-27 03:57
> @daffl ,
> 
> I noticed that this happens because of socket transport **upgrade** from **polling to websocket** that's when you will see two login events.
> 
> another thing i noticed that if i run feathers server and client **locally** than **i don't see two login event** i.e in same local network; if i put client and server apart via **internet** than only **i see two login events** that's may be because of network latency.
> 
> I figured two possible **workaround** for this to prevent two login events.
> 
> 1. In feathers client if you configure socket with **upgrade false** than you will not see two login events
> 2. Or if you put configure transport in this order than also you will not see two login events **transports: [ 'websocket','polling']**
> 
> I've right now used transport in revers order i.e. fallback approach; so i'm not getting two login events.
> I know this is temporary fix ideally socket should prevent that OR it should fire two logout in conjunction to that

@vinaykharecha where you changed order of transports? Thanks!

**Comment by vinaykharecha** [comment] 2019-02-27 09:25
@matiaslopezd ,

Order of transports needs to be changed on client side not server side.
On client side code where you are configuring socket io at that time you need to pass option.
Following is example snippet; in that replace "https://feathers.domain.com" with your feathers server url 

```javascript
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const io = require('socket.io-client');
const app = feathers();
const socket = io("https://feathers.domain.com", {
    transports: ['websocket','polling'],
    forceNew: true
});

app.configure(socketio(socket));
```

**Comment by matiaslopezd** [comment] 2019-02-27 09:37
@vinaykharecha thanks you! :smile:

**Comment by daffl** [comment] 2019-06-06 17:39
Closing since this should no longer be happening in Feathers v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.

**Closed by daffl** 2019-06-06 17:39 UTC
Labels: Authentication, Bug

**Comment by matiaslopezd** [comment] 2019-06-06 22:49
@daffl new version? :scream:

**Comment by SharpBCD** [comment] 2020-02-27 00:44
I have this problem again and I use v4.
my config:
    "@feathersjs/authentication-client": "^4.5.1",
    "@feathersjs/feathers": "^4.5.1",
    "@feathersjs/socketio-client": "^4.3.11",

` Authentication successful for:  xyz  // console.log from authenticate
New connection request. event is: login // from handleConnection
Adding authentication information to connection: xyz // from handleConnection
New connection request. event is: login
Adding authentication information to connection: xyz 
Anonymous connection request // from channels, app.on('connection',.... but the connection is known
User mircea@vhci.ro has joined 6 channels // from channels, app.on('login',.....
User mircea@vhci.ro has joined 6 channels
`
