### ISSUE TITLE
config folder at root instead of custom folder

### ISSUE THREAD

**Issue by woodgates** [feathersjs/feathers#987] opened 2018-09-09 23:18 UTC
### Steps to reproduce
Hi.
I have this repo trying to make nuxt to work with feathers3.2 and its CLI.
https://github.com/woodgates/feathers-nuxt

The configuration is at "server/config" folder. As set in the documents I have my app.js with

```js
const path = require('path');
process.env['NODE_CONFIG_DIR'] = path.join(__dirname, 'config/');
```

When I create the first service with "feathers generate services" all works good except for the database configuration which is stored in the root/config folder instead of root/server/config.

So when I run npm run dev I got 
TypeError: Path must be a string. Received undefined

### Expected behavior
The database configuration should be stored on the root/server/config/default.json file.

### Actual behavior
The database configuration is stored on the root/config/default.json file.

### System configuration

**Module versions** (especially the part that's not working):
part of package.json:
  "directories": {
    "lib": "server",
    "test": "test/"
  },
  "dependencies": {
    "@feathersjs/configuration": "^2.0.2",
    "@feathersjs/express": "^1.2.5",
    "@feathersjs/feathers": "^3.2.1",
    "feathers-nedb": "^3.1.0",,
    "nuxt": "^1.4.2",

**NodeJS version**:
8.11.4
**Operating System**:
I working with Linux Mint 19.

**Browser Version**:
Chromium
**React Native Version**:

**Module Loader**:
npm

**Comment by daffl** [comment] 2018-09-10 15:39
It is important that this happens _before_ the `const configuration = require('@feathersjs/configuration')` call.

**Comment by woodgates** [comment] 2018-09-10 18:09
@daffl 
Its before. This is part of the app.js
```
'use strict'
const path = require('path');
process.env['NODE_CONFIG_DIR'] = path.join(__dirname, 'config/');

const compress = require('compression');
const helmet = require('helmet');
const cors = require('cors');
const logger = require('./logger');


const feathers = require('@feathersjs/feathers')
const configuration = require('@feathersjs/configuration');
```

**Comment by woodgates** [comment] 2018-09-12 19:05
@daffl 
I dont want my configuration in two places. I want the configuration to be at "server/config" folder but the feathers cli is ignoring this.

**Comment by daffl** [comment] 2018-09-12 19:59
I don't understand what the problem is then. If you set

```js
const path = require('path');
process.env['NODE_CONFIG_DIR'] = path.join(__dirname, 'config/');

const configuration = require('@feathersjs/configuration')l
```

The expected folder will be `config/` _within_ the folder of `app.js` (usually `src/`, so `root/src/config`). I just tested this with the [feathers-chat](https://github.com/feathersjs/feathers-chat) and it works as expected.

If you want it at `root/config` you do not have do anything. If you want it at `root/server/config` it has to be `process.env['NODE_CONFIG_DIR'] = path.join(__dirname, '..', 'server', 'config/');`

**Comment by woodgates** [comment] 2018-09-13 16:53
Hi @daffl 

I forgot to mention that my app.js is at the server folder.
root/server/app.js
root/server/config/default.js

Does this change anything?

**Comment by daffl** [comment] 2018-09-13 17:10
It shouldn't. I also just cloned your repository and everything seems to be working fine so I really don't understand what the problem is. The error `TypeError: Path must be a string. Received undefined` is happening in a default setup if `app.get('public')` isn't set (during favicon setup in https://github.com/feathersjs/feathers-chat/blob/master/src/app.js#L31) but you appear to have it removed.

**Comment by woodgates** [comment] 2018-09-13 22:45
Hi @daffl 
According to Configuration docs:
"e.g., In server/app.js:
process.env['NODE_CONFIG_DIR'] = path.join(__dirname, 'config/')
const configuration = require('@feathersjs/configuration')
The above code is portable, so you can keep your config/ directory with the rest of your Feathers files. It will work, for example, even if you change the directory from server/ to amazing-server, etc."

This is what happens when I create the first service:
```
jorge@jorge-VirtualBox:~/Dropbox/www/feachat2$ feathers generate service
? What kind of service is it? NeDB
? What is the name of the service? messages
? Which path should the service be registered on? /messages
? What is the database connection string? nedb://../data
   create config/default.json                         <==== this should modify server/config/default.json not create a new file
   create server/services/messages/messages.service.js
    force server/services/index.js
   create server/models/messages.model.js
   create server/services/messages/messages.hooks.js
   create test/services/messages.test.js
```

**Comment by daffl** [comment] 2018-09-13 23:05
Because the generator does not run the application there is no way for it to know about the change that has been made to `NODE_CONFIG_DIR`.

A pull request that adds support for a `directories.config` in https://github.com/feathersjs/feathers/blob/master/packages/generator-feathers/generators/app/configs/package.json.js#L23 and uses that when writing the configuration file (`this.pkg.directories.config || 'config'` in https://github.com/feathersjs/feathers/blob/master/packages/generator-feathers/generators/connection/index.js#L110) would be welcome.

**Comment by daffl** [comment] 2019-01-05 19:11
This has been released in the latest `@feathersjs/cli`.

**Closed by daffl** 2019-01-05 19:11 UTC
Labels: Generator, Hacktoberfest, Help Wanted
