### ISSUE TITLE
Error typescript dev build on fresh feathers initialization

### ISSUE THREAD

**Issue by ilomon10** [feathersjs/feathers#2127] opened 2020-11-14 07:14 UTC
### Steps to reproduce

```bash
# Install feathers cli
$ npm install -g @feathers/cli

# Check version
$ feathers --version    # 4.4.2

# Generate feathers app
$ feathers generate app    # typescript

# Start app
$ npm start    # working
info: Feathers application started on http://localhost:3030

# Run feathers in development
$ npm run dev    # and it gets error

# but it can quick solve by saving app.js until error not showing
```

### Expected behavior
Running typescript development smoothly without any build error

### Actual behavior
```bash
$ npm run dev

> ts-node-dev --no-notify src/

[INFO] 14:51:20 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 4.0.5)
TypeError: fn.call is not a function
    at Function.configure (PROJECT_DIR/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (PROJECT_DIR/src/app.ts:45:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (PROJECT_DIR/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-43301233573183673.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at require.extensions.(anonymous function) (/tmp/ts-node-dev-hook-43301233573183673.js:59:20)
    at Object.nodeDevHook [as .ts] (PROJECT_DIR/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[ERROR] 14:51:29 TypeError: fn.call is not a function
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:  `v10.22.1`

**Operating System**: `Debian WSL Windows 10`

**Browser Version**: `Chrome 86.x.x.x`

**React Native Version**: -

**Module Loader**: `ts-node-dev `

**Comment by daffl** [comment] 2020-11-18 22:27
I am not able to reproduce this but recommend

- Removing `package-lock.json` and `node_modules` and running `npm install` again
- Regenerating the application

**Comment by bwgjoseph** [comment] 2020-11-19 17:55
It seem to be a bug from `ts-node-dev` and it occurs very randomly. See https://github.com/whitecolor/ts-node-dev/issues/209

In my experience, some machine will encounter is more often than others, and there is not yet any definite fix right now. You could revert back to use `ts-node` if it doesn't get better on your machine

**Comment by ilomon10** [comment] 2020-11-21 08:07
> In my experience, some machine will encounter is more often than others, and there is not yet any definite fix right now. You could revert back to use `ts-node` if it doesn't get better on your machine

@bertho-zero how do u implement `ts-node` instead `ts-node-dev` in development mode, like hot reload when file change.

**Comment by bertho-zero** [comment] 2020-11-21 09:42
I don't remember closing this issue, I clicked by mistake.

**Comment by bwgjoseph** [comment] 2020-11-21 16:21
You lose the `hot-reload` for now but at least you still can develop

**Comment by daffl** [comment] 2020-11-21 16:43
I still think it can be closed since it isn't really a Feathers issue and the related problem to keep track of is linked.

**Closed as completed by daffl** 2020-11-21 16:43 UTC

**Comment by ilomon10** [comment] 2020-12-05 04:59
> It seem to be a bug from `ts-node-dev` and it occurs very randomly. See [whitecolor/ts-node-dev#209](https://github.com/whitecolor/ts-node-dev/issues/209)

@daffl @bwgjoseph Confirmed its a bug for specific machine, when run on another machine its working fine.
