### ISSUE TITLE
 Set up wss, there is error

### ISSUE THREAD

**Issue by feathers-wing** [feathersjs/feathers#2038] opened 2020-08-05 15:12 UTC
My settings are as follows：

```
const server_https = https.createServer({
    key: fs.readFileSync('cert/xxxx.key'),
    cert: fs.readFileSync('cert/xxxxx.pem')
  }, app).listen(443);
  app.setup(server_https); 
  server_https.on('listening', () => {
    console.log(`https://${host}:${port}`);
  });

  let server_wss = new WebSocket.Server({ server: server_https });
  app.setup(server_wss);
  server_wss.on('connection', (ws) => {
     console.log(`wss://${host}:${port}`);
   });

```

But the report was wrong：

```
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
     at WebSocketServer.completeUpgrade (/home/node_modules/_ws@7.3.1@ws/lib/websocket-server.js:267:13)
     at WebSocketServer.handleUpgrade (/home/node_modules/_ws@7.3.1@ws/lib/websocket-server.js:245:10)
     at Server.upgrade (/home/node_modules/_ws@7.3.1@ws/lib/websocket-server.js:89:16)
     at Server.emit (events.js:203:15)
     at Server.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
     at onParserExecuteCommon (_http_server.js:567:14)
     at onParserExecute (_http_server.js:513:3)
```

Want to know how to set the wss to connect！！！

**Comment by daffl** [comment] 2020-08-08 17:52
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment] 2020-08-11 20:45
Closing since the issue does not include the complete application setup. Feathers itself currently only supports websockets through Socket.io or Primus.

**Closed as completed by daffl** 2020-08-11 20:45 UTC
