### ISSUE TITLE
Can not add route with placeholder, using version 5.0-pre3

### ISSUE THREAD

**Issue by fredvb** [feathersjs/feathers#2327] opened 2021-04-30 23:57 UTC
### Steps to reproduce

Use 5.0-pre3

Assuming we have a Message service:
```
const app = feathers();

// Register the message service on the Feathers application
app.use('messages', new MessageService());
```

I wouldn't be able to write a FlagMessageService like so anymore: 
```
app.use('messages/:messageId/flag', new FlagMessageService ());
```

Nor would I be able to specify it like so: 
```

app.use('messages/:messageId/flag', new FlagMessageService ());
```

But I could specify it like so:
```
app.use('messages/:__id/flag', new FlagMessageService ());
```

This seems to not be documented in the Migration to v5 instructions, and I'm not sure if it's intended to be limit the user on this or not.

When using `:id` in the path, I'd get this error: `Can not add route with placeholder ':id' because placeholder ':__id' already exists`
This is why I assumed using `:__id` would work and it seems to unblock the initialization of the app. 

### Expected behavior
It would be nice if we could specify any route params as we wish, as we could in v4. 

### Actual behavior
Getting an error in the form of: `Can not add route with placeholder ':id' because placeholder ':__id' already exists`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** 
Verison 5.0-pre3

**NodeJS version**:
N/A

**Operating System**:
N/A

**Browser Version**:
N/A

**React Native Version**:
N/A

**Module Loader**:
N/A

**Comment by daffl** [comment] 2021-05-01 00:39
This is definitely a regression in the new built-in radix tree router that should be fixed. I just have to get the semantics right because a

```js
app.use('messages', new MessageService());
app.use('messages/:messageId/flag', new FlagMessageService ());
```

is fine since you can always say which request belongs where, but a

```js
app.use('messages', new MessageService());
app.use('messages/:messageId', new SomeMessageService ());
```

wouldn't work because you couldn't tell if going to `messages/something` is a `SomeMessageService.find()` or a `MessageService.get('something')`

**Comment by fredvb** [comment] 2021-05-01 01:15
Correct, the 2nd case you mentioned is probably a user error. I'm not expecting the latter case to be valid and the error that is given is probably accurate.

**Closed as completed** 2021-05-09 16:06 UTC
Labels: Bug
