### ISSUE TITLE
Can't figure out how to create service with hooks but no endpoint

### ISSUE THREAD

**Issue by SephReed** [feathersjs/feathers#1524] opened 2019-08-23 19:23 UTC
I've been searching all over, trying everything I can, but I can't figure out how to create a service with hooks that does not revolve around an endpoint.

I have a function, `createService(hooks)`.  I want to do something like this:

```
const service = createService(someHooks);
// make this use hooks
console.log(service.find());

app.use("/some-endpoint", service);
```

There is a type `feathers.Service` which is returned by `app.service("some-endpoint")`, but I can't seem to create that type (or get ahold of it) except through endpoint.  Everything else will return a regular `Service` type which has no `.hooks()` function.

Here's what I've got so far:
```
public createService(db, hooks) {
	const out = service({
		Model: db,
		name: 'myTable'
	});
        // out.hooks() does not exist
        // (new Service(out).hooks() does not exist
        // (new AdapterService(out).hooks() does not exist
        // can not add hooks to service without endpoint? 
	return out;
}
```

**Comment by daffl** [comment] 2019-08-23 20:45
Duplicate of https://github.com/feathersjs/docs/issues/1323

**Closed by daffl** 2019-08-23 20:45 UTC
