### ISSUE TITLE
Update typings for @feathersjs/authentication

### ISSUE THREAD

**Issue by yeager-j** [feathersjs/feathers#1155] opened 2019-01-03 16:37 UTC
```typescript
import { express } from '@feathersjs/authentication';
```

TypeScript compiler shows an error:

```
Error:(3, 10) TS2305: Module '/node_modules/@types/feathersjs__authentication"' has no exported member 'express'.
```

If I use `// @ts-ignore` it works as expected. Documentation shows that package should export `express` as well as `hooks`, `passport`, and `socket` but ONLY `hooks` is listed.

```typescript
// node_modules/@types/feathersjs__authentication/index.d.ts
export namespace AuthHooks {
    interface HashPassOptions {
        passwordField: string;
    }

    interface RestrictOptions {
        ownerField: string;
        idField: string;
    }

    interface Hooks {
        authenticate(strategies: string[] | string): Hook;

        /**
         * The `verifyToken` hook will attempt to verify a token.
         * If the token is missing or is invalid it returns an error.
         * If the token is valid it adds the decrypted payload to hook.params.payload which contains the user id.
         * It is intended to be used as a before hook on any of the service methods.
         *
         */
        verifyToken(options?: any): Hook;

        /**
         * The populateUser hook is for populating a user based on an id.
         * It can be used on any service method as either a before or after hook.
         * It is called internally after a token is created.
         *
         */
        populateUser(options?: any): Hook;

        /**
         * The `restrictToAuthenticated` hook throws an error if there isn't a logged-in user by checking for the `hook.params.user` object.
         * It can be used on any service method and is intended to be used as a before hook.
         * It doesn't take any arguments.
         *
         */
        restrictToAuthenticated(): Hook;

        /**
         * `restrictToOwner` is meant to be used as a before hook.
         * It only allows the user to retrieve resources that are owned by them.
         * It will return a *Forbidden* error without the proper permissions.
         * It can be used on `get`, `create`, `update`, `patch` or `remove` methods.
         *
         */
        restrictToOwner(options?: RestrictOptions): Hook;

        /**
         * The `hashPassword` hook will automatically hash the data coming in on the provided passwordField.
         * It is intended to be used as a before hook on the user service for the create, update, or patch methods.
         *
         */
        hashPassword(options?: HashPassOptions): Hook;
    }
}
```

**Comment by NickBolles** [comment] 2019-01-14 20:12
@yeager-j Where and why are you importing express from `@feathers-js/authentication`? If you help me understand so that I can reproduce this I can include this in some of the other typing improvements I'm gonna do

**Comment by daffl** [comment] 2019-05-08 22:29
Closing since v4 authentication will also have its typings built in.

**Closed by daffl** 2019-05-08 22:29 UTC
