### ISSUE TITLE
how to use nested routers

### ISSUE THREAD

**Issue by mastertinner** [feathersjs/feathers#207] opened 2016-01-18 10:24 UTC
Trying to use nested routers to accomplish a cleaner file structure like so:

```javascript
'use strict';

const feathers = require('feathers');
const itemsService = require('./items/service');
const router = new feathers.Router();

router.all('/items', itemsService);

module.exports = router;
```

results in an error: `TypeError: Route.all() requires callback functions but got a [object Object]`. Am I doing something wrong or is `feathers.Router()` not ready to consume a feathers service? I have used the same service directly from the feathers `app` so it should be valid.

**Comment by jamesjnadeau** [comment] 2016-01-18 10:54
I think the following line is wrong:
```
router.all('/items', itemsService);
```

Should be 
```
router.use('/items', itemsService)
```

Not sure about your nested file structure... as you don't mention that :)

**Comment by mastertinner** [comment] 2016-01-18 11:04
Thanks for the the quick anser, @jamesjnadeau. I tried `router.use('/items', itemsService);` which resulted in `TypeError: Router.use() requires middleware function but got a Object`.

my folder structure is the following:

```
/
|-- bin
|-- test
|-- src
    |-- v1
        |-- common
        |   |-- datasources
        |   |--  middleware
        |
        |-- module
            |-- items
            |   |-- service.js
            |   |-- model.js
            |
            |-- otherItems
                |-- service.js
                |-- model.js
 ```

which i chose because it reflects the structure of my API's URL (e.g. `https://my-api.com/v1/module/items`).

**Comment by jamesjnadeau** [comment] 2016-01-18 11:24
@mastertinner Can you please provide the contents of your `./items/service` I think your problem lies there.

**Comment by mastertinner** [comment] 2016-01-18 12:02
```javascript
'use strict';

const Item = require('./model');

const itemService = {
  find,
  create,
  remove
};

/**
 * @param {object} params query parameters
 * @param {function} callback callback function
 * @returns {void}
 */
function find(params, callback) {
  Item
    .find(params.query)
    .exec(callback);
}

/**
 * @param {object} data data to post
 * @param {object} params query parameters
 * @param {function} callback callback function
 * @returns {void}
 */
function create(data, params, callback) {
  const queryOptions = {
    new: true,
    upsert: true,
    runValidators: true
  };

  Item
    .findOneAndUpdate({id: data.id}, data, queryOptions)
    .exec(callback);
}

/**
 * @param {object} id ID of the object to remove
 * @param {object} params query parameters
 * @param {function} callback callback function
 * @returns {void}
 */
function remove(id, params, callback) {
  if (id === null) {
    Item
      .remove(params.query)
      .exec(callback);
  } else {
    Item
      .findOneAndRemove({_id: id})
      .exec(callback);
  }
}

module.exports = itemService;

```

**Comment by jamesjnadeau** [comment] 2016-01-18 12:20
I think this line:
```
const itemService = {
  find,
  create,
  remove
};
```
should be
```
const itemService = {
  find:find,
  create:create,
  remove:remove
};
```

**Comment by mastertinner** [comment] 2016-01-18 12:29
That's actually valid ES6 syntax: http://es6-features.org/#PropertyShorthand which can be interpreted by Node.js 4.0.0 and higher.

**Comment by jamesjnadeau** [comment] 2016-01-18 14:27
ya, good luck then, not sure at this point.

**Comment by mastertinner** [comment] 2016-01-18 14:36
ok, thanks for your effort!

**Comment by daffl** [comment] 2016-01-18 16:08
Unfortunately Router can't use services, only an application instance can (with `app.use`). Basically for REST APIs, a service can be considered as its own router. The problem is that with something like `router.use(service)` we won't know what the service path is so it is impossible to set up Sockets for it.

If you would like to use sub-routes that can be done by using sub-apps:

```
// api.js
module.exports = feathers().use('/todos', todoService);

// app.js
var main = feathers();
var api = require('./api');

main.use('/api', api);
```

Now your service will be exposed at `/api/todos`.

**Comment by daffl** [comment] 2016-01-18 16:21
Another note: In 1.x you will still have to call `api.setup()` manually and the websocket routes will not be updated (meaning you still listen to things like `socket.on('todo created')`) like this:

```js
// api.js
module.exports = feathers().use('/todos', todoService);

// app.js
var main = feathers();
var api = require('./api');

main.use('/api', api);

var server = main.listen(8080);
api.setup(server);
```

In v2 this will be `socket.on('api/todo created')` and you won't have to call `api.setup` (see https://github.com/feathersjs/feathers-commons/pull/14)

**Comment by mastertinner** [comment] 2016-01-18 17:11
Thanks, @daffl. Couldn't the `mergeParams` property of the Express router solve that problem? http://expressjs.com/en/4x/api.html#router

**Comment by daffl** [comment] 2016-01-18 18:41
I'm not sure but I think it just passes `req.params` right? The problem is that we have to get a reference to the root application in order to call `app.setup(server)` to set up services and socket listeners. We could add a `router.setup(server)` that you'd have to call manually like

```js
const router = new feathers.Router();

router.use('/items', itemsService);

app.use('/api', router);

var server = app.listen(8080);
router.setup(server);
```

But that is literally exactly the same as creating a sub-application so I don't see a real benefit (it would even be more cumbersome to use than a sub-app in Feathers 2).

**Comment by mastertinner** [comment] 2016-01-18 19:30
I agree. Thanks for the clarification, @daffl!

**Comment by daffl** [comment] 2016-01-19 07:51
Thanks for submitting the issue. Feathers does claim do work like Express so it was actually a great question. I hope that works and it's ok if I close the issue. Let us know if you have any other questions.

**Closed** 2016-01-19 07:51 UTC
