### ISSUE TITLE
Feathers client app.authenticate throws UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): * Error *

### ISSUE THREAD

**Issue by RileyDavidson-Evans** [feathersjs/feathers#547] opened 2017-04-09 02:38 UTC
### Steps to reproduce

Configure feathers server and client,

on client run:
`app.authenticate({
      strategy: 'local',
      'email': '*email*',
      'password': '*password*'
    })
      .then((result, s) => console.log(result, s))
      .catch(e => console.log(e));`

### Expected behavior
Promise is returned with token for valid credentials or error

### Actual behavior
Promise is not returned and throws log error on server:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): * Error *

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment] 2017-04-10 06:48
This looks like a duplicate of https://github.com/feathersjs/feathers-authentication/issues/476 (further discussion in that issue).

**Closed by daffl** 2017-04-10 06:48 UTC
