### ISSUE TITLE
Calling method on non-existent service from Client over sockets times out.

### ISSUE THREAD

**Issue by edwardmsmith** [feathersjs/feathers#490] opened 2016-12-29 18:56 UTC
### Steps to reproduce

Using a feathers application setup to use sockets...  

Note also, that I found this using a client created through create-react-app to which I added the feathers client.  I have not created a generic test case.  I could, if needed.

In the feathers client, call a method on a service that is not configured on the server.  For instance, if the `foo` service does not exist on the server, on the client, invoke `foo.find().then(...).catch(...)`

### Expected behavior
I would expect an immediate error (similar to an http 404) to be returned to the client over the socket, informing the client that there is no `foo` service.

### Actual behavior
We receive a promise timeout after 5 seconds:

`Error fetching organizations Error: Timeout of 5000ms exceeded calling foo::find`

### System configuration

Server-side:  Feathers app created using the generator.
Client-side: Create-react-app generated client with feathers added.

**Module versions** (especially the part that's not working): 

├── feathers@2.0.3
├── feathers-authentication@1.0.2
├── feathers-authentication-jwt@0.3.0
├── feathers-authentication-local@0.3.2
├── feathers-camayak@0.0.0 extraneous
├── feathers-configuration@0.4.1
├── feathers-errors@2.5.0
├── feathers-hooks@1.7.1
├── feathers-hooks-common@2.0.3
├── feathers-nedb@2.6.0
├── feathers-rest@1.5.2
├── feathers-socketio@1.4.2

**NodeJS version**: v6.6.0

**Operating System**:  OSX El Cap.

**Browser Version**: Chrome 55

**Module Loader**: Webpack?

**Comment by daffl** [comment] 2016-12-30 21:17
The problem is that there is no way to know over websockets if you are sending (and waiting) for an event that doesn't exist and most websocket libraries don't have a catchall event so the only way to deal with unknown events is a timeout on the client.

We are discussing a proposal to solve this with a separate `subscribe` event in #421 so I'm going to close this issue to track progress (and further discussion) in #421.

**Closed by daffl** 2016-12-30 21:17 UTC
