### ISSUE TITLE
Token is undefined

### ISSUE THREAD

**Issue by knappdev** [feathersjs/feathers#569] opened 2017-05-04 00:01 UTC
### Steps to reproduce

Configure the client:
export const restApp = feathers()
  .configure(rest(host).superagent(superagent))
  .configure(hooks())
  .configure(authentication({
    storage: AsyncStorage,
  }))

Fetch access token using: 
const token = restApp.get('accessToken');
(User is already authenticated in this case)

token undefined

But if fetched with some delay then the valid token will be returned

### Expected behavior
Token should be available after configuring the feathers client

### Actual behavior
Token is null 

**Module versions** (especially the part that's not working):
"feathers": "^2.1.1",
    "feathers-authentication-client": "^0.3.1",
    "feathers-errors": "^2.7.1",
    "feathers-hooks": "^2.0.1",
    "feathers-rest": "^1.7.2",
    "feathers-socketio": "^1.6.0",

**React Native Version**:
"react-native": "0.43.4",

**Comment by knappdev** [comment] 2017-05-06 10:13
Is there are workaround for this issue? because of this issue, authentication request is dispatched to the server every time user opens the app. I have observed it takes some time for this(const token = restApp.get('accessToken');) API to return token. Am I missing something here?

**Comment by eddyystop** [comment] 2017-05-06 12:51
You may be an answer faster posting this in the feathers-authentication repo.

**Comment by knappdev** [comment] 2017-05-08 15:52
@eddyystop Thanks for the suggestion. I will do that

**Comment by daffl** [comment] 2017-05-08 19:02
The token will not be set until you call `app.authenticate()` (with no parameters). I remember @marshallswain added it but maybe we should make it even more obvious in the documentation at https://docs.feathersjs.com/api/authentication/client.html#

**Comment by daffl** [comment] 2017-05-09 19:49
Duplicate of https://github.com/feathersjs/feathers-authentication/issues/500

**Closed by daffl** 2017-05-09 19:49 UTC

**Comment by knappdev** [comment] 2017-05-10 00:52
@daffl Thanks for getting back. But app.authenticate() will make server request and I don't want to overload the server every time user launches the application. Or is that how it should be?

**Comment by marshallswain** [comment] 2017-05-10 00:56
If you are using web sockets, it js to be that way.

**Comment by knappdev** [comment] 2017-05-11 00:54
@marshallswain  server request happening for restApp client as well. 
**Code:**
export const restApp = feathers()
.configure(rest(host).superagent(superagent))
.configure(hooks())
.configure(authentication({
storage: AsyncStorage,
}))
