### ISSUE TITLE
Messages not received by client after `authenticate` hook.

### ISSUE THREAD

**Issue by bartram** [feathersjs/feathers#1671] opened 2019-11-08 09:10 UTC
Using feathersjs in a react-native project, running the `authenticate` hook appears to cause `context` to lose the reference to the socket connection, so it is not possible for that connection to join channels in subsequent hooks (or in the service functions themselves), and events are not received by the client. I've narrowed it down the cause of my issue to the line below:

https://github.com/feathersjs/feathers/blob/43c654cc3ba8f797e15a9db07a1e3b64d5f2da99/packages/authentication/src/hooks/authenticate.ts#L54

Passing `params` as the first argument of `merge` (and getting rid of the empty object, thus mutating `params` instead of copying it) solves the issue in my case:

    context.params = merge(params, omit(authResult, "accessToken"), {
      authenticated: true
    });

**Comment by daffl** [comment] 2019-11-08 14:14
Duplicate of https://github.com/feathersjs/feathers/issues/1629

**Closed** 2019-11-11 16:28 UTC

**Comment by daffl** [comment] 2019-11-11 17:10
Fixed in [v4.3.11](https://github.com/feathersjs/feathers/releases/tag/v4.3.11).
