### ISSUE TITLE
Generate app misses dependencies

### ISSUE THREAD

**Issue by eduardoroliveira** [feathersjs/feathers#2551] opened 2022-02-08 16:59 UTC
### Steps to reproduce

```bash
$ feathers generate app
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name order-add
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Jest
? This app uses authentication No
```

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [X] Tell us what broke. The more detailed the better.

I had to install the following libraries manually in order to have the project working: 

```bash
npm install @typescript-eslint/eslint-plugin@latest --save-dev
npm install axios
npm i --save-dev @types/jest
npm install shx --save-dev
npm i --save-dev @types/serve-favicon
npm i --save-dev @types/compression
npm i --save-dev @types/cors
```

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

The `feather generate app` should install all dependencies and work without any additional library installation.

### Actual behavior

I had to install the following libraries manually in order to have the project working: 

```bash
npm install @typescript-eslint/eslint-plugin@latest --save-dev
npm install axios
npm i --save-dev @types/jest
npm install shx --save-dev
npm i --save-dev @types/serve-favicon
npm i --save-dev @types/compression
npm i --save-dev @types/cors
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
{
  'order-add': '0.0.0',
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Operating System**: MacOs Monterey 12.2

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment] 2022-02-08 17:20
This is a temporary and not reproducible problem with Yeoman (which still exits gracefully even if the installation fails).  Re-running the generator or installing the missing dependencies will usually fix it (also see https://github.com/feathersjs/cli/issues/90 and https://github.com/feathersjs/cli/issues/232). Closing since we are moving away from Yeoman (#2414) and hopefully avoid those kinds of problems in the future.

**Closed as completed by daffl** 2022-02-08 17:20 UTC
