### ISSUE TITLE
socketio crashes server if using with feathers-authentication

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/feathers#664] opened 2017-09-01 17:48 UTC
### Steps to reproduce
I have the following setup on server side:

```js
// @flow
import config from 'config';
import path from 'path';
import compress from 'compression';
import cors from 'cors';
import feathers from 'feathers';
import configuration from 'feathers-configuration';
import hooks from 'feathers-hooks';
import rest from 'feathers-rest';
import socketio from 'feathers-socketio';
import bodyParser from 'body-parser';
import errorHandler from 'feathers-errors/handler';
import auth from 'feathers-authentication';
import jwt from 'feathers-authentication-jwt';
import middleware from './middleware';
import routes from './routes';
import services from './services';

const app: Object = feathers();
const authConfig = config.get('auth');
const configRoot: string = path.resolve(__dirname, '..');

app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(configuration(configRoot))
  .configure(hooks())
  .configure(rest())
  .configure(socketio({ wsEngine: 'uws' }))
  .configure(auth(authConfig))
  .configure(jwt({ service: config.get('auth').userEndpoint }))
  .configure(services)
  .configure(middleware)
  .configure(routes)
  .use(errorHandler());

export default app;
```

and when I'm trying to connect from client to socket:

```js
// @flow
import socketio from 'feathers-socketio/client';
import feathers from 'feathers/client';
import io from 'socket.io-client';

const socket = io('http://localhost:3035');
const api = feathers();

api.configure(socketio(socket));

socket.on('connect', () => console.log('Connected!'));

export default api;
```
it crushes server side with the error:
`TypeError: Cannot read property 'on' of undefined`

But if I will commit on server side lines with authentication configs:
```js
  // .configure(auth(authConfig))
  // .configure(jwt({ service: config.get('auth').userEndpoint }))
```

everything works fine. What could be the problem? am I doing something wrong?

**Module versions**:
    "feathers": "^2.1.7",
    "feathers-authentication-client": "^0.3.1",
    "feathers-hooks": "^1.8.1",
    "feathers-localstorage": "^1.0.0",
    "feathers-rest": "^1.7.2",
    "feathers-socketio": "^2.0.0",

**NodeJS version**:
6.11

**Comment by teddy-error** [comment] 2017-10-04 04:11
From what you posted, it looks like an issue with your babel configuration. `io` is not returning a Manager instance.

Node is still using modules as it is yet to support `import` and you are using `flow` so you must be transpiling your code, yes?

**Comment by sarkistlt** [comment] 2017-10-04 16:54
yes correct I do, here is babel config:

```JSON
{
  "presets": [
    "flow",
    "stage-0",
    "env"
  ],
  "env": {
    "production": {
      "comments": true,
      "compact": true
    }
  }
}
```

**Comment by daffl** [comment] 2018-01-04 23:46
I'm going to close this since I think it should be fixed by upgrading to the latest release. If not, please feel free to reopen (ideally with a full stack trace and/or a project to clone and reproduce the issue).

**Closed by daffl** 2018-01-04 23:46 UTC
