### ISSUE TITLE
Nuxt not working after generating service

### ISSUE THREAD

**Issue by jarnojellesma** [feathersjs/feathers#633] opened 2017-07-27 13:30 UTC
### Behavior
I have a project combining Nuxt for server-side rendering VueJs, and Feathers as the API server. Currently everything works with an Nedb service. But after generating a Sequelize service I'm receiving the following error upon starting the Nuxt server:

`(node:30149) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_1_nuxt___default.a is not a constructor
`

Here is a repo, try to generate a service, and after that do **npm run dev-client**.
https://github.com/jarnojellesma/feathers-nuxt-error

**I solved it** by removing node_modules, and doing npm install again. So there must be going something wrong by generating the service.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"feathers": "^2.1.1",

**NodeJS version**:
v6.10.3

**Operating System**:
Ubuntu 16.04

**Browser Version**:
Version 59.0.3071.86 (Official Build) (64-bit)

**Nuxt Version**:
"nuxt": "^1.0.0-alpha.5",

**Module Loader**:
    "node": ">= 6.0.0",
    "yarn": ">= 0.18.0"

**Comment by daffl** [comment] 2017-08-07 18:56
It looks like it was an npm error. Closing since the link to the repository is no longer working. Please reopen if it is fully reproducible and specifically related to Feathers.

**Closed by daffl** 2017-08-07 18:56 UTC

**Comment by woodgates** [comment] 2018-09-09 22:17
Hi.
I solved this in a very simple way that is working. That a look at server/app.js and server/middleware in my repo.
https://github.com/woodgates/feathers-nuxt
