### ISSUE TITLE
Didn't get $Populate working

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [feathersjs/feathers#669] opened 2017-09-11 08:30 UTC
### Steps to reproduce
serverside used ref:referencedmodelname (with or without full path) with type String:
branch01ID:{ type: String, ref: 'branch01' },
on client added the query param:
this.query['$populate'] = [{path:'branch01'}]; I also tried with or without full path AND also as shown in doc with just $populate:'branch01'
for rxjs i used both always and smart

### Expected behavior
Query result should include data from branch01 document 

### Actual behavior
Data from branch01 is not there, no error thrown

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
CLIENT
"feathers-client": "^1.2.4",
"feathers-reactive": "^0.4.1",
"rxjs": "^5.1.0",
SERVER:
"feathers": "^2.1.3",
    "feathers-authentication": "^1.2.4",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.3.4",
    "feathers-blob": "^1.0.5",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.8.1",
    "feathers-hooks": "^2.0.1",
    "feathers-hooks-common": "^3.5.3",
    "feathers-memory": "^1.1.0",
    "feathers-mongodb": "^2.9.0",
    "feathers-mongoose": "^5.1.1",
    "feathers-rest": "^1.7.3",
    "feathers-socketio": "^2.0.0",
    "mongoose": "^4.10.7",
**NodeJS version**:
6.1.0
**Operating System**:
OS-X
**Browser Version**:
CHROME/SAFARI
**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment] 2017-09-11 15:04
Duplicate of https://github.com/feathersjs/feathers-reactive/issues/60

**Closed by daffl** 2017-09-11 15:04 UTC
