### ISSUE TITLE
Postgres SSL

### ISSUE THREAD

**Issue by naptiv** [feathersjs/feathers#239] opened 2016-02-26 15:51 UTC
I'd like to use an Heroku remote db, so regarding [https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js](url) I have to add an ?ssl=true at the end of the DB URL.

Unfortunately, I still have an ssl is off error at npm start

**Comment by daffl** [comment] 2016-02-26 16:32
How does your setup look like? Are you using feathers-sequelize or feathers-knex?

**Comment by naptiv** [comment] 2016-02-26 17:24
Hi @daffl  I'm using  feathers-sequelize
```
{
  "host": "localhost",
  "port": 3030,
  "postgres": "postgres://user:pw@ec2-54-83-29-133.compute-1.amazonaws.com:5432/de5mmehm3q7rtc?ssl=true",
  "public": "../public/",
  "auth": {
    "token": {
      "secret": "......"
    },
    "local": {}

  }
}
```

**Comment by naptiv** [comment] 2016-02-26 17:34
I first tried business-stack where the config file is  https://github.com/enspiral-craftworks/business-stack/blob/master/config/development.js

With this boilerplate I just had to add a `ssl:true` inside `db:connection`

Maybe is there a way to define the connection this way with feather ?

**Comment by ekryski** [comment] 2016-02-26 17:36
@naptiv can you post the error please? I haven't had a chance to test this with Heroku Postgres yet but might later today or this weekend.

**Comment by naptiv** [comment] 2016-02-26 17:58
Sure, 
```
Feathers application started on localhost:3030
Unhandled rejection SequelizeConnectionError: no pg_hba.conf entry for host "ip", user "username", database "dbname", SSL off
    at /Users/naptiv/unlock/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:101:20
    at null.<anonymous> (/Users/naptiv/unlock/api/node_modules/pg/lib/client.js:176:5)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/naptiv/unlock/api/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by ekryski** [comment] 2016-02-26 22:12
@naptiv thanks. That does help a bit. I'll see if I can reproduce.

**Comment by naptiv** [comment] 2016-02-29 10:44
I tried to deploy Feathers to Heroku in order to avoid the SSL parameter but I ran into an other issue.

When running on heroku I have to use the port specified in the PORT environment variable : `process.env.PORT` which can't be set in the json file.

**Comment by daffl** [comment] 2016-02-29 15:45
You should be able to. On Heroku you set `NODE_ENV` to `production` and then you can in `config/production.json` set `"port": "PORT"` which will try to read that environment variable. This is documented in https://github.com/feathersjs/feathers-configuration but I still have to add it to the main documentation.

**Comment by daffl** [comment] 2016-03-02 03:41
Hopefully this works. I'm going to close this one. Feel free to reopen or add another issue if you have any other questions.

**Closed by daffl** 2016-03-02 03:41 UTC
Labels: bug

**Comment by alex-1244** [comment] 2016-04-27 20:27
Hello
i have similar problem i guess
i'm using windows
for development run i have such a configuration for postgres:
`var sequelize = new Sequelize(config.test.name, config.test.login, config.test.password,{
      host:config.test.host,
      dialect:"postgres",
      logging: false
    });`

and here is my config
`var config={
	"test":{
		name:"buget",
		login:"alext",
		password:"***",
		host:"localhost"
	}
};

module.exports=config;`

and on running the code i have the error 
`unhandled rejection sequelizeconnectionerror the server does not support SSL connections`.

**Comment by alex-1244** [comment] 2016-04-27 20:29
By the way on ubuntu i have all the same code and it's running with no problems
So i have two suggestions
1 - windows specific issue
2 - misconfiguration of postgres server on windows

**Comment by Caravus** [comment] 2016-08-27 22:36
So, no SSL?

**Comment by daffl** [comment] 2016-08-28 09:55
Of course. It looks like you need to use the [pg-native driver for Sequelize](http://docs.sequelizejs.com/en/1.7.0/docs/usage/) ([here](https://github.com/sequelize/sequelize/issues/956) is another issue).

**Comment by daffl** [comment] 2016-08-29 09:00
The option to set once changed to the `pg-native` driver [is](https://twitter.com/pbounaix/status/770025052641320961)

```js
dialectOptions: { ssl: true }
```

**Comment by loganpowell** [comment] 2017-05-16 01:02
Just posting here what @amingilani posted in the [thread](https://github.com/sequelize/sequelize/issues/956) @daffl shared:

@mickhansen you're a beautiful person. By the way, nowhere in the issue does it say dialectOptions, and the dialectOptions in the docs don't show an ssl option.

I'm just going to leave this snippet for someone like me that runs into problems with heroku:

`var sequelize = new Sequelize(process.env.DATABASE_URL, {
  dialect: 'postgres',
  dialectOptions: {
    ssl: true
  }
});`
