### ISSUE TITLE
Executing CRUD requests in service event handlers

### ISSUE THREAD

**Issue by domagoj03** [feathersjs/feathers#1576] opened 2019-09-23 13:19 UTC
Is it possible to execute service's CRUD methods in event handlers of other services? 

Here is an example:
I want to insert service1 model based on service2 data.
Same behavior is observed in Promise equivalent, nothing in then, nothing in catch. Same behavior is observed if we use `context.app.service(...)` to get service.
``` service1.service.js
  // Initialize our service with any options it requires
  app.use('/service1', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service1 = app.service('service1');
  service1.hooks(hooks);

  const service2 = app.service('service2');
  service2.on('created', async (request, context) => {
    console.log('Created.'); // This part is executed and result is visible in the console. 
    try {
      await service.create({...}); // This is not executed.
    } catch (e) {
      console.log(e); // This is not executed.
    }
  });
```

### Expected behavior
Execute create request or throw an error.

### Actual behavior
Nothing.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** "@feathersjs/feathers": "^3.3.1"

**NodeJS version**: 10.16.1

**Operating System**: Manjaro Linux

**Module Loader**: npm 6.9.0

**Comment by domagoj03** [comment] 2019-09-23 13:39
Seems like this has something to do with using app in external scripts (say a database seeder) because whether I want to execute service's methods in hooks or as part of an event handler - they don't work. 

``` 
// script.js
const app = require('../src/app');

exports.seed = () => {
      return app.service('service')
        .create({...})
}
```

In this example `.create()` is executed without problems, data is inserted and any registered hooks are called, but if I do say `context.app.('service2').create()` it won't work. In normal app flow, i.e. http request this works.

**Comment by daffl** [comment] 2019-09-24 17:25
I am not seeing any problems with your first code example so a complete example to reproduce would be helpful. Usually creating related entries would happen in a hook though (since event handlers might trigger multiple times [e.g. when using feathers-sync](https://github.com/feathersjs-ecosystem/feathers-sync/#caveats)).

**Comment by domagoj03** [comment] 2019-09-25 10:30
> I am not seeing any problems with your first code example so a complete example to reproduce would be helpful. Usually creating related entries would happen in a hook though (since event handlers might trigger multiple times [e.g. when using feathers-sync](https://github.com/feathersjs-ecosystem/feathers-sync/#caveats)).

Here is the repo https://github.com/domagoj03/curly-happiness

**Comment by daffl** [comment] 2019-09-25 16:47
How would I reproduce your issue?

**Comment by domagoj03** [comment] 2019-09-25 16:50
By running knex's seed command (`knex seed:run`), we would expect the `seeds/demo.js` to run and insert a row. We would then expect the event handler in `src/services/address.service.js:23` to insert another row. We can see that the event handler is called, but the row is not inserted.

**Comment by daffl** [comment] 2022-10-18 23:38
I recently tested something similar with the [latest prerelease](https://dove.feathersjs.com) (which also comes with better built-in Knex support) and it worked as expected. Closing since it has been open for a while.

**Closed by daffl** 2022-10-18 23:38 UTC
Labels: CLI
