### ISSUE TITLE
Using socketio client method cause create event to fire twice

### ISSUE THREAD

**Issue by zhouanbo** [feathersjs/feathers#923] opened 2018-08-05 06:00 UTC
When I use a client socketio method to create a record: 
```
client.service('user').create({_id: ..., ...})
```
and add a before hook to console.log('created') on the server, the server will output "created" twice and report a duplicate id error. When I switch to the rest request:
```
fetch('https://endpoint', {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    'Authorization': token
                  },
                  body: JSON.stringify({_id: ..., ...}),
                })
``` 
The server will output "created" only once and report no error.

My client setup code:
```
const socket = io('...', {
  transports: ['websocket'],
  forceNew: true
})
const client = feathers()

client.configure(socketio(socket))
client.configure(auth({storage: AsyncStorage}))
client.configure(reactive({
  idField: '_id',
  listStrategy: 'always' 
}))
```

**Comment by zhouanbo** [comment] 2018-08-05 06:03
Meanwhile, the server side
```
app.service('users').create()
```
method is unaffected by this behavior.

**Comment by daffl** [comment] 2018-08-06 22:16
Two things to try to narrow things down a little:

1. Try removing `forceNew` from the websocket connection
2. Try removing `feathers-reactive` (`client.configure(reactive(...`)

**Comment by zhouanbo** [comment] 2018-08-06 23:47
Hi @daffl , 
Thanks for the suggestions, I've tried the following and the results are:
1. removed forceNew, create event still fires twice.
2. removed feathers-reactive, create event still fires twice.
3. Using 'always' in feather-reactive actually stop watched events to fire twice. If I remove 'always', for example if I create the article (which will be created twice with duplicate id error), the watched article list will add two more of the same new article.

**Comment by zhouanbo** [comment] 2018-08-07 04:01
@daffl ,
I'm surprised as well but it actually happens in browser.
Steps I did:
1. npx create-react-app my-app
2. cd my-app
3. yarn add socket.io-client
4. yarn add @feathersjs/feathers
5. yarn add @feathersjs/socketio-client
6. vi src/App.js
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import io from 'socket.io-client'
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'

const socket = io('https://endpoint', {
  transports: ['websocket'],
  forceNew: true
})
const client = feathers()
client.configure(socketio(socket))

class App extends Component {

  componentDidMount() {
    client.service('test').create({_id: 'aaa'})
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```
7. yarn start
and on the server:
```
error: BulkWriteError: E11000 duplicate key error collection: database.test index: _id_ dup key: { : "aaa" }
```

**Comment by zhouanbo** [comment] 2018-08-07 04:07
Btw, my server looks like this:
```
const path = require('path');
const favicon = require('serve-favicon');
const compress = require('compression');
const helmet = require('helmet');
const cors = require('cors');
const logger = require('./logger');

const feathers = require('@feathersjs/feathers');
const configuration = require('@feathersjs/configuration');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');

const middleware = require('./middleware');
const services = require('./services');
const appHooks = require('./app.hooks');
const channels = require('./channels');

const mongodb = require('./mongodb');
const authentication = require('./authentication');

const registry = require('./registry');

process.on('unhandledRejection', (reason) => {
  console.log('Reason: ' + reason);
});

const app = express(feathers());

// Load app configuration
app.configure(configuration());

app.configure(socketio({
  pingInterval: 10000,
  pingTimeout: 50000
}));
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet());
app.use(cors());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));

// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());

app.configure(mongodb);

// Configure other middleware (see `middleware/index.js`)
app.configure(middleware);

app.configure(authentication);

// Set up our services (see `services/index.js`)
app.configure(services);
// Set up event channels (see channels.js)
app.configure(channels);

app.configure(registry);

// Configure a middleware for 404s and the error handler
app.use(express.notFound());
app.use(express.errorHandler({ logger }));

app.hooks(appHooks);

module.exports = app;

```
where registry is the file I do my own middlewares. Services are basically auto-generated.

**Comment by daffl** [comment] 2018-08-07 21:57
Can you share a complete repository with the client side code to reproduce the problem? Does this e.g. also happen if you follow the [chat application guide](https://docs.feathersjs.com/guides/chat/readme.html)?

**Comment by zhouanbo** [comment] 2018-08-08 04:35
Hi @daffl ,
Thanks for the continuous help. I set up a repo at https://github.com/zhouanbo/feathers-client-test, but I'm sorry I don't have time to exactly follow the chat tutorial at this time because I'm under a deadline. I'm suspecting it's the mongodb driver because it seems this is the only difference.

**Comment by daffl** [comment] 2018-08-08 17:59
It does not look like I can use that example, I'm just getting an error message. Ideally it would include the server as well because I think that's where the problem is.

**Comment by zhouanbo** [comment] 2018-08-11 13:43
@daffl ,
After some code removal testing, I found out removing this code from the server:
```
app.configure(socketio({
  pingInterval: 10000,
  pingTimeout: 50000
}));
```
solve the problem. The code is suggested by the document to accommodate for Android. Not sure what is exactly the cause tho.

**Comment by Aerlin** [comment] 2018-09-04 00:54
I may be experiencing the same issue with [Socket.io tester](https://github.com/AppSaloon/socket.io-tester) receiving created events twice. 
When connecting, `app.on('connection', connection => {})` fires twice and when creating stuff (via rest) `app.publish((data, hook) => {});` fires once. I assumed the tester app was malfunctioning by connecting twice until I came across this thread.

**Comment by r3gisc** [comment] 2018-10-21 00:01
> @daffl ,
> After some code removal testing, I found out removing this code from the server:
> 
> ```
> app.configure(socketio({
>   pingInterval: 10000,
>   pingTimeout: 50000
> }));
> ```
> solve the problem. The code is suggested by the document to accommodate for Android. Not sure what is exactly the cause tho.

Same here with a vue.js frontend. i wanted to use socket calls along feathers. So far it's not possible because of this bug :-(. Removing this socket config from node is a workaround

**Comment by daffl** [comment] 2019-07-17 23:22
This appears to have been an authentication issue which has been fixed in the v4 prerelease. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html) on how to upgrade.

**Closed by daffl** 2019-07-17 23:22 UTC
Labels: Bug, Transport
