### ISSUE TITLE
Socket-io will not reconnect to React Native background apps

### ISSUE THREAD

**Issue by unfrgivn** [feathersjs/feathers#1832] opened 2020-02-27 11:34 UTC
### Steps to reproduce

In a sample RN app on an iOS device (also happens on a couple xcode simulators so I don't think the version matters)

1. Connect to featherjs via socket-io client and send/receive events as normal
2. Then background the app but don't close it
3. Turn off the device screen and wait for your set timeout to lapse. I tested with 5000ms, 10000ms and 30000ms but same result on all.
4. Unlock device and the open app still running in the background
5. The `on.connection` event fires and from that point on the socket connection is bricked. You can try to `authenticate()` / `reAuthenticate()` but every action to the feathers client will produce a timeout ->

```
type: "FeathersError"
name: "Timeout"
message: "Timeout of 5000ms exceeded calling create on authentication"
code: 408
className: "timeout"
data: {timeout: 5000, method: "create", path: "authentication"}
```

I see some chatter on **socketio** issues about this that are still open but kinda old. The gist of it is seems like people are having issues with the 2.x versions of of socket-io client and are downgrading the version to fix. But I tried the current v2.3.0, v2.1.1 and v1.7.4 with same result on all. 

[https://github.com/socketio/socket.io-client/issues/1276](https://github.com/socketio/socket.io-client/issues/1276)
[https://github.com/socketio/socket.io-client/issues/1193#issuecomment-393542923](https://github.com/socketio/socket.io-client/issues/1193#issuecomment-393542923)

### My client config

I tried several variations of enabling and disabling these options but made no difference. Several of the suggestions talk about disabling long-polling by setting the `transports` option, but that is already done (as suggested by the featherjs docs).  

```
{
      transports: ['websocket'], 
      forceNew: true,
      upgrade: false,
      pingTimeout: 3000, 
      pingInterval: 5000, 
}
```

### To-do

- I still need to strip down everything in my app to just a basic RN generator app + featherjs to rule out any other packages
- Test on Android 

### System configuration

**Module versions**: 

- @feathersjs/socketio-client@4.5.1
- socket.io-client@2.3.0 | 2.1.1 | 1.7.4

**NodeJS version**: 12.14.1

**Operating System**: iOS 13.3.1 / 12.4.1 / 10.3.0 (I did not test Android yet)

**React Native Version**: 0.59.10

**Comment by unfrgivn** [comment] 2020-02-28 00:35
I set up a brand new React Native app with only feathers and that appears to work when locking the phone and reconnecting, so I need to start tacking on packages until I find the conflict. But considering this seems to be an issue others are having, perhaps the eventual solution will yield something useful.

**Comment by daffl** [comment] 2020-04-07 15:51
Would be great to see any finding you can share but I'm going to close this issue since I don't think there is something Feathers specific that can be done at the moment.

**Closed by daffl** 2020-04-07 15:51 UTC

**Comment by unfrgivn** [comment] 2020-04-07 16:37
Yea sorry @daffl I ran a bunch of tests on this at the time, but ultimately I couldn't track it down and everything is now working for me with `socket.io-client@2.3.0` without removing any packages out of my app. It's possible minor updates ran though over the course of trying new things. 

You remove your node_modules folder, clear caches and rebuild enough times and all of a sudden you've changed way too many variables to identify.

**Comment by su14iman** [comment] 2020-09-05 21:51
@unfrgivn Hello
I had this problem three days ago and now I have found the solution.
The problem is that the application in Debug all its good and without problems, but when I have Build apk file, I loses the connection to the server.
The solution was for me, add this line:
`android:usesCleartextTraffic="true"` in `AndroidManifest.xml`
* like this examble:
https://stackoverflow.com/questions/54418709/react-native-android-release-apk-cant-receive-data-from-internet

best regards
