### ISSUE TITLE
throwing an NotAuthenticated error in authenticate() no longer resolve the promise

### ISSUE THREAD

**Issue by SharpBCD** [feathersjs/feathers#2117] opened 2020-11-08 22:23 UTC
### Steps to reproduce
I have a custom Firebase auth strategy. Simplifying the issue:
```
async authenticate(authentication, param) {
   throw new NotAuthenticated(`test error`);
}
```
I no longer receive the error in client side, the promise is never solved.

Things to consider:
 - this use to work, not sure on which update it stopped working, but a few months ago was working.
 - I do receive the error on app.hooks so it works until there.
 - I do have the following code as my last lines in app.js:
```app.use(express.errorHandler({logger}));
app.hooks(appHooks);```

### Expected behavior
Promise is resolved when I throw the error so that I receive the error in client-side instead of timeout error.

### Actual behavior
`create auth` promise is not resolved, client receive time-out instead of the error.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 4.5.10

**NodeJS version**: 12.3.1

**Operating System**: Windows

**Comment by daffl** [comment] 2020-11-09 01:52
I can't reproduce this with the latest versions in the Feathers chat, it works as expected. Please provide a complete repository that can reproduce your issue.

**Comment by daffl** [comment] 2020-11-09 20:00
One likely culprit is Socket.io 3.0. You can __not__ upgrade the Socket.io client to version 3.

**Comment by SharpBCD** [comment] 2020-11-10 00:54
I have "socket.io-client": "^2.3.0" on client side. 2.3.1 installed version. 
Uhh... not sure how to start debugging this.

**Comment by daffl** [comment] 2020-11-10 17:48
You can 

- Try to reproduce your problem with the [feathers-chat repository](https://github.com/feathersjs/feathers-chat)
- Downgrade your versions until things are working again
- Try to remove as many things from your existing project to see when things stop working or creating a minimal example to reproduce

**Comment by daffl** [comment] 2020-11-13 18:56
I am however going to close this since it can't be reproduced. Feel free to reopen when you have more information.

**Closed as completed by daffl** 2020-11-13 18:56 UTC

**Comment by SharpBCD** [comment] 2020-11-26 03:49
Found the bug! A library called `device-detector-js` was braking the error handler. I use it in the `parse()` function to get the users device info. It probably install some error handler or something like that.

**Comment by daffl** [comment] 2020-11-26 04:32
Thank you for sharing! This always helps folks that might run into the same problem.
