### ISSUE TITLE
init is not a function

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers#1204] opened 2019-02-10 14:21 UTC
Not sure if this a bug or not as can't reproduce but trying to understand why it would happen as it's an error that seems to crop up reasonably regularly.

The error I get is 

> Uncaught (in promise): TypeError: t.init is not a function
> TypeError: t.init is not a function

My angular service is as below

```
export class ApiService {
  private feathers: any;
  constructor(
    private http: HttpClient,
  ) {
    this.feathers = feathers(); // Error occurs here
    const restClient: Transport = rest(environment.host);

    this.feathers
      .configure(
        restClient.angularHttpClient(this.http, { HttpHeaders: HttpHeaders })
      ));
  }
}
```

**Comment by daffl** [comment] 2019-02-10 17:55
This should be fixed via https://github.com/feathersjs/feathers/pull/1153 in `@feathersjs/feathers` v3.3.1 and later.

**Comment by dottodot** [comment] 2019-02-10 18:22
I'm using `@feathersjs/client` 3.7.3

**Comment by dottodot** [comment] 2019-02-10 18:26
And the api it's connecting to uses 3.3.1

**Comment by dottodot** [comment] 2019-02-10 18:32
Look like the client doesn't have the same fix.

```
function createApplication() {
  var app = {}; // Mix in the base application

  Proto.mixin(Application, app);
  app.init();
  return app;
}
```

**Comment by daffl** [comment] 2019-02-10 18:47
The `@feathersjs/client` version that has the fix is v3.7.8 (current latest)

**Comment by dottodot** [comment] 2019-02-10 18:55
OK thanks, yarn normally picks up when an update is available, but hasn't done for this.

**Comment by daffl** [comment] 2019-02-11 15:23
Maybe. We were only seeing this for `app.init` and the above fixed all errors that were Feathers related. It could be that whatever browser plugin or library causes affects other libraries as well.

**Comment by daffl** [comment] 2019-02-17 17:10
Closing since I think the Feathers related issue should be fixed in the latest version.

**Closed by daffl** 2019-02-17 17:10 UTC

**Comment by joacub** [comment] 2019-06-13 16:28
the error is still, same error here on latest version on some circustances, not always

**Comment by dottodot** [comment] 2019-06-13 16:30
Yeah I still get it on a regular basis, never have found the cause.

**Comment by joacub** [comment] 2019-06-13 16:31
yes is very stranger, i got the error in some circustance is dificult to cathc the error i need put one event to catch this and addEventlistener('error')

**Comment by joacub** [comment] 2019-06-13 16:44
im try to follow the bundle requires and aparently some index not exist for example on my bundle n(213) the index 213 not exist on any file

**Comment by daffl** [comment] 2019-06-13 23:28
As I mentioned, it's usually some browser extension messing with built in JavaScript prototypes. Don't know what else can be done here other than #1153 unless someone can provide a reliably reproducible use case.

**Comment by joacub** [comment] 2019-06-29 03:51
O have a day around of 150 weird about this so not is a small bug, I think this need a solution or change the init function to other name
